# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'covid19_map' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
	pod 'Firebase/Analytics'
  pod 'GoogleMaps'
  pod 'SideMenu'
  pod 'IQKeyboardManagerSwift'
  pod 'Closures'
  pod 'OTPTextField'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'ReachabilitySwift'
  pod 'SwiftMessages'
  pod 'MBProgressHUD'
  pod 'Google-Maps-iOS-Utils'
  pod 'SwiftKeychainWrapper'

  # Pods for covid19_map

end
